print(f"Введите целое число:",end=" ")
num=int(input())
print(f"В какую систему перевести (2, 8, 16)?",end=" ")
system=input()
print()
print()
print(f"Число {num} в разных системах:")
print(f"Десятичная: {num}")
print(f"Двоичная: {num:b}")
print(f"8-битное представление: 00{num:b}")