print(f"Введите ваш возраст: ",end="")
ege=int(input())
print(f"Введите ваш рост в метрах: ")
height=float(input())
print(f"\nВаши данные:")
print(f"Возраст: {ege} лет")
print(f"Рост: {height} м")
print(f"Введите ваш вес в кг:",end=" ")
weight=int(input())
bmi = weight / (height * height)
print(f"Ваш ИМТ: {bmi:.1f}")
